transfered gdocs writeup to markdown
OWASP/www-project-integration-standards pull request #11
Opened 2020-02-09 18:56 UTC by northdpole

this is a simple article we put together with @ThunderSon , it can serve as a basis for this project

2020-02-12 15:18 UTC, ThunderSon requested changes
After validating the missing image, I will add numbering on the figures to make it easier to reference. We'll be good to send it out as a first release for other's reviews.

2020-02-12 15:18 UTC, ThunderSon commented on writeups/owasp_in_sdlc/owasp_in_sdlc.md
> +In case of internal development and if the organisation maps Features to Epics, the [Security Knowledge Framework](https://securityknowledgeframework.org/) can be used to facilitate this process by l
This is missing a picture, no?

2020-02-12 15:18 UTC, ThunderSon commented on writeups/owasp_in_sdlc/owasp_in_sdlc.md
> +Customer commission's application that aggregates data from a number of stores offering a unified API for all data querying and retrieval. The users of the system will be customer employees. The appl
This sentence was a bit hard to read. Could we maybe improve it?

2020-02-16 19:05 UTC, northdpole commented on writeups/owasp_in_sdlc/owasp_in_sdlc.md
> +In case of internal development and if the organisation maps Features to Epics, the [Security Knowledge Framework](https://securityknowledgeframework.org/) can be used to facilitate this process by l
it's a link

2020-02-17 17:21 UTC, ThunderSon approved these changes
I'd say the first picture can be cut shorter, and the last one. It is good to be merged though.

2020-02-17 17:21 UTC, merged